export const mockEvents = [
    {
        id: 'evt_001',
        title: '桜島ナイトフェス',
        descriptionShort: '桜島をバックに開催される夜の音楽と光の祭典。地元の食材を使った屋台も多数出店。',
        imageUrl: 'https://placehold.co/600x400/222222/FFFFFF/png?text=Sakurajima+Night',
        startAt: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(), // Tomorrow
        venueName: '桜島溶岩なぎさ公園',
        area: '桜島',
        priceText: '入場無料',
        isFree: true,
        kidsOk: true,
        parking: true,
        after18: true,
        indoor: false,
        photogenic: true,
        englishSupport: true,
        curatorNote: 'フェリーからの夜景も最高です！',
        lat: 31.59,
        lng: 130.60,
        address: '鹿児島県鹿児島市桜島横山町',
        bookingUrl: 'https://example.com/sakurajima'
    },
    {
        id: 'evt_002',
        title: '仙巌園 菊まつり',
        descriptionShort: '大名庭園を彩る数千本の菊のアート。歴史ある雰囲気の中で秋の訪れを感じられます。',
        imageUrl: 'https://placehold.co/600x400/dddddd/333333/png?text=Sengan-en',
        startAt: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(),
        venueName: '仙巌園',
        area: '吉野',
        priceText: '大人1000円',
        isFree: false,
        kidsOk: true,
        parking: true,
        after18: false,
        indoor: false,
        photogenic: true,
        englishSupport: true,
        curatorNote: '着物での散策がおすすめ。',
        lat: 31.61,
        lng: 130.57,
        address: '鹿児島県鹿児島市吉野町9700-1'
    },
    {
        id: 'evt_003',
        title: '鹿児島ラーメン王座決定戦・前哨戦',
        descriptionShort: '県内の人気ラーメン店が集結！あなたの投票でNo.1が決まる熱い戦い。',
        imageUrl: 'https://placehold.co/600x400/ff9900/ffffff/png?text=Ramen+Battle',
        startAt: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString(),
        venueName: 'ウォーターフロントパーク',
        area: '天文館エリア',
        priceText: 'チケット制 1杯800円',
        isFree: false,
        kidsOk: true,
        parking: false,
        after18: true,
        indoor: false,
        photogenic: false,
        englishSupport: false,
        curatorNote: 'お腹を空かせて行きましょう！',
        lat: 31.59,
        lng: 130.56
    },
    {
        id: 'evt_004',
        title: '天文館ミリオネーション',
        descriptionShort: '天文館公園を彩る100万球のイルミネーション。冬のデートスポットとして人気。',
        imageUrl: 'https://placehold.co/600x400/000033/ffff00/png?text=Millionation',
        startAt: new Date(new Date().setDate(new Date().getDate() + 4)).toISOString(),
        venueName: '天文館公園',
        area: '天文館',
        priceText: '無料',
        isFree: true,
        kidsOk: true,
        parking: false,
        after18: true,
        indoor: false,
        photogenic: true,
        englishSupport: false,
        curatorNote: '光のトンネルは必見です。',
        lat: 31.58,
        lng: 130.55
    },
    {
        id: 'evt_005',
        title: '維新ふるさと館 特別展',
        descriptionShort: '明治維新の立役者たちに焦点を当てた特別展示。未公開資料も公開。',
        imageUrl: 'https://placehold.co/600x400/553311/ffffff/png?text=Meiji+Restoration',
        startAt: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
        venueName: '維新ふるさと館',
        area: '加治屋町',
        priceText: '大人300円',
        isFree: false,
        kidsOk: true,
        parking: true,
        after18: false,
        indoor: true,
        photogenic: false,
        englishSupport: true,
        curatorNote: '歴史好きにはたまりません。',
        lat: 31.58,
        lng: 130.54
    }
];
